Repository spinnaker/front50, pull requests merged in 2020-08, with the labels that each got.

#916 fix(misc): Recover application permission also when we undo delete op…
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/AdminOperations.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/AdminController.java
  front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/AdminControllerSpec.groovy
Labels: auto merged, ready to merge

#915 feat(pipeline): (optionally) validate that a saved pipeline is not stale
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
Labels: auto merged, ready to merge

#911 refactor(gcs): Rewrite the GcsStorageService
  front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/ApplicationPermissionDAO.java
  front50-gcs/front50-gcs.gradle
  front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
  front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsProperties.java
  front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
  front50-gcs/src/main/java/com/netflix/spinnaker/front50/retry/GcsProviderOperationException.java
  front50-gcs/src/main/kotlin/com/netflix/spinnaker/front50/model/GcsStorageService.kt
  front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/FakeStorageRpc.kt
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt
  front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java
  front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java
  front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageService.kt
  front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
  front50-swift/src/main/java/com/netflix/spinnaker/front50/model/SwiftStorageService.java
  gradle.properties
  settings.gradle
Labels: auto merged, ready to merge

#922 fix(exceptions): Use kork's NotFoundException
  front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/ApplicationPermissionsService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/ServiceAccountsService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/exception/NotFoundException.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/ItemDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/ApplicationDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/ApplicationService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/DefaultApplicationDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/notification/DefaultNotificationDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineStrategyDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfoService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningService.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/project/DefaultProjectDAO.java
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/project/ProjectDAO.java
  front50-core/src/test/groovy/com/netflix/spinnaker/front50/ServiceAccountsServiceSpec.groovy
  front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationServiceSpec.groovy
  front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoServiceSpec.groovy
  front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningServiceSpec.groovy
  front50-gcs/src/main/kotlin/com/netflix/spinnaker/front50/model/GcsStorageService.kt
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt
  front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java
  front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAO.groovy
  front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
  front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineStrategyDAO.groovy
  front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineTemplateDAO.java
  front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisProjectDAO.groovy
  front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAOSpec.groovy
  front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAOSpec.groovy
  front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineStrategyDAOSpec.groovy
  front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisProjectDAOSpec.groovy
  front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java
  front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageService.kt
  front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
  front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageServiceTests.kt
  front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
  front50-swift/src/main/java/com/netflix/spinnaker/front50/model/SwiftStorageService.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/DeliveryController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/NotificationController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/ReorderPipelinesController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/SnapshotsController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.java
  front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.java
  front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
  front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy
Labels: ready to merge

#924 fix(provider/Oracle): Cache issue related to Oracle Object Storage (bp #886)
  front50-oracle/front50-oracle.gradle
  front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java
Labels: ready to merge

#925 chore(dockerfile): various Dockerfile cleanups
  Dockerfile.compile
  Dockerfile.java8
  Dockerfile.slim
  Dockerfile.ubuntu
  Dockerfile.ubuntu-java8
Labels: ready to merge

#930 feat(gitRepoArtifact): include migration to move subpath to location field
  front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/MoveSubpathToLocationMigration.java
  front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/MoveSubpathToLocationMigrationSpec.groovy
Labels: ready to merge

#934 fix(gcs): Fix startup error when bucketLocation is not specified
  front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsProperties.java
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/FakeStorageRpc.kt
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTestConfiguration.kt
  front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt
  front50-gcs/src/test/resources/minimal-gcs-account.yml
Labels: auto merged, backport-candidate, ready to merge

#927 feat(notification): Add Microsoft Teams notification support
  front50-core/src/main/java/com/netflix/spinnaker/front50/model/notification/NotificationDAO.java
Labels: auto merged, ready to merge
